# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstblog', '0006_auto_20170712_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myfirstblog.Label'),
        ),
    ]
